init 0 python:
    class Sayori():
        """
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMW0dodk0KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMWNXK0Okxo:',,,,;codxk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMWN0xdlccc::c;'',,,'',colccldkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMWKxlcccccclodo;'',,''''';:;;;;,;lxOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMNkllodddolloddxl;,,,,''....''..'''''cKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMWXdloxxxddxkxxxolodddxxxddl;'.'........dNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMWXxoxkkkddkOOkkO0kxddxxk0KK0kl,........':oOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMWXkx000OkkOOOOO0OOOOOkkk00OkO0ko,......,:::oKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMNKxox0XX0kO000000OOOO0KK0Okxook0Od:,,,:cclolco0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMN0xclk0KKOkKXXKKKX000OO0KKOxddlok0Okkxlldolodc:dOKNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMNKKklxOOKOdkKXXKKXXXK0OkOOOOOkdocoO0OOOxldxodxocd0XXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMKKNOdkkOKOxk0KKK0KKXKKOOXK0OOkxdl:d000OkddkddkdlldXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMM0x0xokOO00kO0KKXK00KXX0OXNNXKOOxo;cOK0OOxxkkOOxollOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMKlllcxOO00OKXKKXXXK0KXKKNWWWWNNX0kdOKK0OOOOOxxddo:oXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMWOo::xkOOOO0NNNXXXNXXKXXNNX0xold0NK0K000Okkkxdddl:dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMM0kxldkxkkOKNNNNNX00XK0KNN0o,...'oO0000OOkxdollllckWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMOxKxoxxxkkdoloONWNXNWNNNWNkodoodxO0OOkxkxdo:;coolxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMOdXOcodxd::c;;:kNWWWWWWWWWX0KKKKK0OOkdddol:,,;cd0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMNO0k::ldocd0xkO0XWWWWWWWWWNNXXXK00kkkxccll:;:oONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMNOkl;:lolok000XNNNNNNWNNNNNNXK0Oxxkkdlll::xXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMNKkxdc,;;:clx0KXXNNNNNNNNNNNNNXX0OOxdxlcox0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMX00kxx:',,,;:lOXXXNX000OOkxOXNXXKOkdldkOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMM0odxd:,;:coxxdx0XNNKdcodxkk0XNXX0kdlloxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMNxll:;oO00NWWWNKKKXNX0kOO0KXNXKOdoodxxxdxOKXNXXK00OO0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMW0ccd0NMMMMMMMMMWXXXKKXXXXXKOxdooodxxddxOxodxxdddddoodONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMW0okNMMMMMMMMMNKOxdolcokOkkoloddodxxxOKNNkdxxxxxxddxkxoxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMNKXWMMMMMMMWOc,''',,,lxxxxlloodxO0KNMMMKdxxxxxxxxxxxxxd0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMWk:,,,,,,,;oOxddolloxO0NMMMMWOdxxdoddddxxxxxd0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMWWMMMKc',;;;;;;:xkl;;cloxdoxkOXMMXkddolododxxdxxxd0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMWXKXXXN0:',;;::::ld:,,':kKOdxd:;cx0OxdoodxooddddxxxdKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMWKOK00K0dc:;;:::::;;cc':OKxodlxkolodxkkO0Okdoddddxdd0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMNOOO0KKXX0xl::::clddxl,;::cONWKddxO0000OOxddddddddo0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMWXKXKKXNNNX0kcclodooc;,lOxoxKK00K000OkxdddddddddooKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMWNOook000k::ll:;lodc:kK00XNNNXXKOxllooodoooododKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMKd:,cdxkd::c:,;;cdd:cOXXXXK0kxdcc:coooooooooldXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMWk;lkkOOkxlc:::,'.:xc.lkkkxooooc;::coooooooooldNMMMMMWNNMMMMMNXWMMMMXOKMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMWk;;lk00Okxxl;;'.,co:.,dkkkxdxxo:,;cooooollllcxNWNXK0OxdxOKNXdcd0WW0l':0WMMMMMMMMMMMMM
        MMMMMMMMMMMMMMWk;,:oddxdddl:,.'cccc:lox000kxddl,;lllllcccllcdko:;,'.,cccclo:;,:od:''.;OWWWWMMMMMMMMM
        MMMMMMMMMMMMMMWO:;:lddddddlc;';cc:lxOOOOkxxxxddl:cllcc::clc:,........';::::;;,,,','...:0klOWMMMMMMMM
        MMMMMMMMMMMMMMMO:;:cloodddlc:;:lc;,col:lxxxxxdddl:ccccccc:::..........'';;;,,,,,'''....,'.;0MMMMMMMM
        MMMMMMMMMMMMMMM0l:::cloodo:;c:;:;;,,,,';ldxdxddddc:::cclllc:'.......'''.',,',,''''.........cXMMMMMMM
        MMMMMMMMMMMMMMMKo:::cllooo,.::..',,',,,,:codddddddoc:coolc:;,'''''''''''''.'''..............xWMMMMMM
        MMMMMMMMMMMMMMMXdccccllooc,.'::....''',,;:cloooooddol::c;;,',,'',,,,,,,,,,''................;KMMMMMM
        MMMMMMMMMMMMMMMKoccccclll:;'',::...''.',;::clllooooooc;;c:,';::ccc:ccllccc:'.....''........ .kMMMMMM
        MMMMMMMMMMMMMMMKc;cccccccc:,';;,:. ....',;::cclllllool;,:::codoooolllllllcc,....,............lWMMMMM
        MMMMMMMMMMMMMMMKl:::ccccclc,',;::,.......';:::cccccccc:;::ldooollcccccccccc,.............    lX0XMMM
        MMMMMMMMMMMMMMM0lcc:cccccc:''colc,.........',;::::::::::::lllllcc::ccc:::::,...........      ',;0MMM
        MMMMMMMMMMMMMMMXd::::cc:c:;;clol:'............',;::::::::cccccc::::::::::::,.........     .....oWMMM
        MMMMMMMMMMMMMMMMNko:,,,;;;:clcll,...,,.''........',,,,;:ccccc:::::::;;;;;;;'..................,0MMMM
        MMMMMMMMMMMMMMMMMMWNKkxdc;::clc;'',oxc'',,,'''''....,::;::::::::;;;;;;;;;;;.......'''.........dWMMMM
        MMMMMMMMMMMMMMMMMMMMMMNx:;;;:::;;l0Xc..',,,,;;,,,'..,;;;:::;;;;,;,;;,,,,,,,...'','...........cXMMMMM
        MMMMMMMMMMMMMMMMMMMMMWk:;;;;:loxOKOo,..',,,,'',,'''..',,,,,,'''',,,,,,,,,,'.................cKMMMMMM
        MMMMMMMMMMMMMMMMMMMMWkc:;;:d0XX0d:'.....',;;;;,,'''....'''''''',,,,,,,,,,,'...........    'dNMMMMMMM
        MMMMMMMMMMMMMMMMMMMM0c,;;cONMXx;.......'',;;;;''''......''''''',,,,,,,,,,,.........       ,xXMMMMMMM
        """
        





