init -20 python in fae_ui:

    SCROLLABLE_MENU_X = 680
    SCROLLABLE_MENU_Y = 40

    SCROLLABLE_MENU_W = 560

    SCROLLABLE_MENU_TXT_TALL_H = 528
    SCROLLABLE_MENU_TXT_MEDIUM_H = 440

    SCROLLABLE_MENU_XALIGN = -0.05

    SCROLLABLE_MENU_TXT_TALL_AREA = (SCROLLABLE_MENU_X, SCROLLABLE_MENU_Y, SCROLLABLE_MENU_W, SCROLLABLE_MENU_TXT_TALL_H)
    SCROLLABLE_MENU_TXT_MEDIUM_AREA = (SCROLLABLE_MENU_X, SCROLLABLE_MENU_Y, SCROLLABLE_MENU_W, SCROLLABLE_MENU_TXT_MEDIUM_H)
    